<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your email address_uploader_email</name>
   <tag></tag>
   <elementGuidId>1bc3d4c8-506a-43bd-bc89-0c81d8a2e5b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploader_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uploader_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e20df680-ef8f-4c16-8266-e568c5c63687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uploader_email</value>
      <webElementGuid>a5eb2908-8bdf-4930-8c95-13ff67f10e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f921ae4c-e0d4-4e6f-901d-f5a35338cef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span12</value>
      <webElementGuid>6495aba8-e721-4670-a8c9-b8c7831231c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploader_email</value>
      <webElementGuid>25653743-90bd-434b-97f6-45647d52c4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploader_email&quot;)</value>
      <webElementGuid>9b71732a-ff6b-4525-8208-086373691dfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploader_email']</value>
      <webElementGuid>444b3919-8bcb-4f5b-b0f2-d13f00a6395a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[2]/input</value>
      <webElementGuid>918902cf-a2bf-4223-8cac-7c3cbea70e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7e99f8c8-04bc-4837-beb6-e7910213f5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'uploader_email' and @type = 'text' and @id = 'uploader_email']</value>
      <webElementGuid>fd170505-062a-4a9b-9cae-accda7e9827c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
