<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Step 3_accept_tos</name>
   <tag></tag>
   <elementGuidId>8e5c8d76-54f8-4664-8bd2-f6b8e95674d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='accept_tos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;accept_tos&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82665edb-ac3b-4966-922d-1590151df3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accept_tos</value>
      <webElementGuid>7e51e99d-845c-4c75-b022-c34df47bf019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dfd0be39-3b91-4056-934d-7da2393149b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f56ff00d-d63b-4502-b695-58d0863a43ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept_tos&quot;)/span[1]/input[1]</value>
      <webElementGuid>eb8be73b-c835-4eb9-888f-53c7bfe22ab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='accept_tos']</value>
      <webElementGuid>65ea5a2d-c1c8-48d4-bb54-ee500625cde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='accept_tos']/span/input</value>
      <webElementGuid>7e0d7cce-51d9-45f7-b1d6-35a101c2020d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>5f286a25-b3c9-48ef-aa5b-db370287233c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'accept_tos' and @type = 'checkbox']</value>
      <webElementGuid>a0880441-1dc6-4f63-86dc-561c84ec31bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
